### ISSUE TITLE
Python Module not Found: Field

### ISSUE THREAD

**Issue by Werni2A** [mhostetter/galois#106]
Hi, your package looks promising wherefore I wanted to give it a try but Python complains about not finding the `field` module.

```bash
  File "/home/aci/.local/lib/python3.8/site-packages/galois/__init__.py", line 7, in <module>
    from .field import *
ModuleNotFoundError: No module named 'galois.field'
```
Should this module be provided by `galois` or by another package? I searched for `field.py` on my file system but without any success.

I use  Ubuntu 20.04.2 LTS (Focal Fossa) as OS with 
```bash
$ python3 --version
Python 3.8.5
```

According to the documentation it should work out of the box with
```bash
python3 -m pip install galois
```
which installed the following version
```bash
$ python3 -m pip list | grep galois
galois                  0.0.15 
```

I hope you can help me out here. Thank you very much :)

PS The code I tried was just the example from the documentation
```python
import numpy as np
import galois

# GF256 = galois.GF(2**8)
# print(GF256)
```

**Comment by Werni2A** [comment]
When I clone the repository and install the package from there it works. Probably `field` is not packaged for PyPI

**Comment by mhostetter** [comment]
Hey, thanks for the report! I can reproduce this issue.

You are correct. It is a packaging issue. I have been silently burned by one of these before, and I thought it put in safeguards, but apparently not. I'll fix the issue, add better testing and safeguards, and release a new version in the next day or two. I'll comment here when I do.

I appreciate you bringing this to my attention. Let me know if you run into any other issues with the library or requested features.

**Comment by Werni2A** [comment]
@mhostetter thank you for the fast fix. I can confirm that it works fine now.
