### ISSUE TITLE
GF._primitive_element should be an element of GF

### ISSUE THREAD

**Issue by kstauffer** [mhostetter/galois#121]
... But it's currently a plain old int. `GF(2**100)._primitive_element ** (2**50)` ate all my RAM. I know that the leading underscore means this is an implementation detail; is there a public way to get my hands on the primitive element?

**Comment by mhostetter** [comment]
Yes. All the "Galois field array class" attributes are listed in [FieldMeta](https://galois.readthedocs.io/en/latest/pages/galois.FieldMeta.html). The leading underscore means private and shouldn't be accessed by a user. The correct property is `GF.primitive_element`. Unfortunately, I've found `ipython` doesn't tab-complete the properties of a Galois field array class. :disappointed: I'm looking into that though.

So in your case, you would access it like this:

```python
In [1]: import galois                                                                          

In [2]: GF = galois.GF(2**100)                                                                 

In [3]: GF.primitive_element                                                                   
Out[3]: GF(2, order=2^100)

In [4]: %time GF.primitive_element ** (2**50)                                                  
CPU times: user 1.6 ms, sys: 0 ns, total: 1.6 ms
Wall time: 1.6 ms
Out[4]: GF(224578514763007752640052891188, order=2^100)

In [5]: a = GF.primitive_element ** (2**50); a                                                 
Out[5]: GF(224578514763007752640052891188, order=2^100)

In [6]: GF.display("poly");                                                                    

In [7]: a                                                                                      
Out[7]: 
GF(α^97 + α^95 + α^94 + α^92 + α^90 + α^88 + α^87 + α^85 + α^82 + α^81 + α^79 + α^78 + α^77 + α^76 + α^75 + α^74 + α^73 + α^70 + α^67 + α^66 + α^65 + α^64 + α^63 + α^62 + α^61 + α^60 + α^59 + α^57 + α^56 + α^53 + α^50 + α^48 + α^47 + α^46 + α^45 + α^40 + α^39 + α^35 + α^32 + α^31 + α^28 + α^25 + α^23 + α^21 + α^20 + α^19 + α^15 + α^11 + α^10 + α^9 + α^5 + α^4 + α^2,
   order=2^100)
```

**Comment by kstauffer** [comment]
Ah! You nailed it: I was misled by ipython not tab-completing. Thanks!

**Comment by mhostetter** [comment]
@kstauffer yeah... That's a big bummer. I really need to find a way to fix that. Ipython is confused because those properties are contained in a metaclass. There *must* be a workaround.

**Comment by kstauffer** [comment]
Is it at easy as defining a `__dir__` method in the metaclass? http://ipython.org/ipython-doc/dev/config/integrating.html
