### ISSUE TITLE
Add Empty as additional constructor to FieldArray

### ISSUE THREAD

**Issue by iyanmv** [mhostetter/galois#201]
I find very useful the additional constructors for FieldArray such as Zeros, Ones or Identity. I miss, however, having an equivalent to the `np.empty`, where entries are not initialized. This is useful when constructing huge arrays that need to be initialized afterwards.

I propose adding a new class method `Empty` to the FieldArray class. I will write a quick PR, and we can continue the discussion there.

**Comment by iyanmv** [comment]
Actually, before I write anything, does this make sense?

**Comment by iyanmv** [comment]
I guess this would contradict all the asserts and `__array_finalize__` method. So maybe it's just easier to use `np.empty`, initialize that object and then create a new GF field from the original one.

**Comment by mhostetter** [comment]
@iyanmv it's a good idea, and I'm open to adding new constructors. With `np.empty()` however, the array values aren't set so they can be any value of the given `dtype`. You're right that it would, in all likelihood, fail the asserts in `__array_finalize__()`. A workaround as you mentioned is:

```python
x = np.empty(shape)
# Initialize x to valid values
x = x.view(GF)
```

Any other thoughts on how this could be done?

**Comment by iyanmv** [comment]
After checking the code more carefully, an array with a certain field can never have invalid values for that finite field, because `__array_finalize__` is always called at some point. So I don't see a way to make a constructor similar to `np.empty()`, because at least for some time, it will have invalid values so there will be a `ValueError` exception.

Another alternative could be a constructor that initializes the array using a function passed as an argument to the constructor. Then we could do what you suggested above.

```python
def NewConstructor(cls, shape, fun, dtype=None):
    dtype = cls._get_dtype(dtype)
    array = np.empty(shape, dtype=dtype)
    fun(array)
    return array.view(cls)
```

**Comment by iyanmv** [comment]
But then, how to pass arguments to this function if needed? It starts to get more difficult than simply do everything on a regular np.array and then at the end convert it to a GF array.

**Comment by mhostetter** [comment]
Do you have an example or use case of using `np.empty()` or the desired `GF.Empty()`? That might help me ponder how to implement it.

Often when initializing, I'll use `GF.Zeros(shape)`. Or if I need a specific value, for instance 17, I'll use `GF(17) * GF.Ones(shape)`.

I very much like the verification that happens when creating or setting an array. Otherwise, it would be very easy to have an "invalid" value in the array and subsequent arithmetic would no longer be meaningful.

**Comment by iyanmv** [comment]
Yes, for example to create a Toeplitz matrix with NumPy, I would do the following:

```python
import numpy as np

matrix = np.empty((rows, columns), dtype=np.uint8)
    for i in range(rows):
        for j in range(columns):
            matrix[i, j] = seed[i - j]
```
for a given `seed`, and known `rows` and `columns`.

**Comment by mhostetter** [comment]
While you *could* add a callback function to your proposed `GF.Empty()` constructor and *could* pass in additional arguments for the callback, my feeling is it's not generally-applicable enough to warrant inclusion in the API.

My thoughts on your use case would be either: 

1) Use `np.empty()` and then cast to a `FieldArray`
```python
matrix = np.empty((rows, columns), dtype=np.uint8)
for i in range(rows):
    for j in range(columns):
        matrix[i, j] = seed[i - j]
matrix = matrix.view(GF)
```

2) Initialize the `FieldArray` with zeros and then overwrite
```python
matrix = GF.Zeros((rows, columns), dtype=np.uint8)
for i in range(rows):
    for j in range(columns):
        matrix[i, j] = seed[i - j]
```

Is `np.zeros()` significantly more costly than `np.empty()`? Just curious.

**Comment by iyanmv** [comment]
Surprisingly, `np.empty()` is slower than `np.zeros()` on my desktop now... I don't understand why. I guess `np.empty()` is not as efficient as just assigning a bunch of memory.

**Comment by iyanmv** [comment]
I was using option 1, but now just change my code to your second suggestion.

**Comment by mhostetter** [comment]
I ran a couple tests and saw `np.zeros()` was 50-100x slower than `np.empty()`, but still took only a handful of microseconds. Due to lack of generality, I'm leaning towards not adding a `FieldArray.Empty()` constructor into the official API. I might reconsider if you have other thoughts / ideas.

**Comment by iyanmv** [comment]
The speedup seems to depend a lot on the platform. I agree, `FieldArray.Zeros()` is good enough, so I close this.
