### ISSUE TITLE
poly.degrees also returns degrees of zero coefficients

### ISSUE THREAD

**Issue by geostergiop** [mhostetter/galois#217]
Hi again Matt and happy new year,

Hope you are healthy. Just came across this one, not sure if it's a bug or intended functionality. the `poly.degrees` function on some polynomial returns all degrees including those with zero coefficient. Example:
```
In:
test = galois.Poly.Degrees([15, 5, 2 , 0])
print(test)

Out:
Poly(x^15 + x^5 + x^2 + 1, GF(2))
```
```
In:
test = galois.Poly.Degrees([15, 5, 2 , 0])
print(test.degrees)

Out:
[15 14 13 12 11 10  9  8  7  6  5  4  3  2  1  0]
```
Maybe this is intended, although I cannot seem to find a reason to get all positions on `.degrees`. I assume the most useful scenario would be to return degrees on coefs != 0 . If this is intended, is there another function to call to only get the no-zero degrees?

Happy 2022,
George

**Comment by mhostetter** [comment]
Hey George,

Yes, it is by design. The accessor you're looking for is [`Poly.nonzero_degrees`](https://galois.readthedocs.io/en/stable/api/galois.Poly.html#galois.Poly.nonzero_degrees).

I can see the confusion since `Poly.Degrees` creates a polynomial from nonzero degrees/coefficients you might expect `Poly.degrees` to return the nonzero coefficients. However, I set it up so that `.degrees` and `.coeffs` are one-for-one pairs and `.nonzero_degrees` and `.nonzero_coeffs` are one-for-one pairs.

Perhaps renaming `Poly.Degrees` to `Poly.NonzeroDegrees` would be more consistent, but it seems a bit verbose. :confused:

**Comment by geostergiop** [comment]
Thanks!

**Comment by mhostetter** [comment]
@geostergiop are you trying to do something like this?

```python
In [21]: import numpy as np                                                                                               

In [22]: poly1 = galois.Poly.Degrees([5, 4, 3, 0]); poly1.coeffs                                                          
Out[22]: GF([1, 1, 1, 0, 0, 1], order=2)

In [23]: poly2 = galois.Poly.Degrees([5, 3, 2, 0]); poly2.coeffs                                                          
Out[23]: GF([1, 0, 1, 1, 0, 1], order=2)

# Array the same shape as the coefficients and True when they're different
In [24]: poly1.coeffs != poly2.coeffs                                                                                     
Out[24]: array([False,  True, False,  True, False, False])

# The number of different coefficients
In [25]: np.sum(poly1.coeffs != poly2.coeffs)                                                                             
Out[25]: 2
```

**Comment by geostergiop** [comment]
Yep, that's way better, thanks! Actually, I am trying to build a characteristic polynomial of an element A in a GF, seems though you don't have anything up and runnin on that matter, right?
For reference from [wikipedia](https://en.wikipedia.org/wiki/Characteristic_polynomial):
![image](https://user-images.githubusercontent.com/8626213/148788603-9d6cb77f-d2b8-4753-a840-e77361765e6b.png)

Two element matrices may have the same characteristic polynomial but different minimal polynomials, e.g.
![image](https://user-images.githubusercontent.com/8626213/148788891-2817d186-901c-4a6c-abe4-9b8e8e24199d.png)

**Comment by mhostetter** [comment]
@geostergiop no I don't yet, but open a new issue and we can add it. It could maybe be a method `FieldArray.characteristic_poly()` for square matrices only.
