### ISSUE TITLE
Missing dependency on min-requirements.txt

### ISSUE THREAD

**Issue by iyanmv** [mhostetter/galois#230]
Commit 4a498ba09d89d46e3dd62d867033c180a2b3ee68 added `typing_extensions` to `setup.cfg`. However, it was not included in `min-requirements.txt`. This causes an import error when working locally with the repo and a virtualenv.

I just realized now when I was checking all the new things added during Christmas :smile: Great work with the type hints by the way! :clap:

**Comment by mhostetter** [comment]
Thanks for pointing this out! I wasn't sure if it was needed there since it's only for typing, but clearly it is.

Also, please let me know if you find issues / inconsistencies in the type hints. I usually use / test this library in ipython, so I rarely see the type hints.

**Comment by iyanmv** [comment]
Sure, sure, I will do. Actually, typing is quite nice if you use an IDE that supports them.
