### ISSUE TITLE
Extend power operation

### ISSUE THREAD

**Issue by iyanmv** [mhostetter/galois#232]
This is something that can be done with `numpy.array` but not with `galois.FieldArray` at the moment.

```python
import numpy as np
import galois

2**np.arange(10)
array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

GF = galois.GF(2**9)
2**GF.Range(0, 10)
# TypeError: Operation 'power' requires the first operand to be a GF(2^9) array, not <class 'int'>.

GF(2)**GF.Range(0, 10)
# TypeError: Operation 'power' requires the second operand to be an integer array, not <class 'numpy.ndarray over GF(2^9)'>.
```

I think some kind of casting can be done here, similarly to `numpy`. What do you think?

**Comment by mhostetter** [comment]
This *is* intentional behavior. I can explain my rationale and you can let me know if it makes sense or could be improved.

The type checking for arithmetic is *strict*. From your example, what does an integer raised to a finite field element mean?
Or, what does a finite field element raised to a finite field element exponent mean?

I believe the only types that make sense are: integer raised to integer power or finite field element raised to an integer power. This is because the exponent represents an integer number of times to multiply the base.

Here's an example using `GF(2^9)`. Here `x = GF(3)` isn't the integer 3 -- it's the field element `α + 1` which has the integer representation of 3. So what does `2^(α + 1)` really mean? You know?

```python
In [1]: import galois                                                                                                            

In [2]: GF = galois.GF(2**9, display="poly")                                                                                     

In [3]: GF(3)                                                                                                                    
Out[3]: GF(α + 1, order=2^9)

# What is expected?
In [4]: GF(2)**GF(3)                                                                                                             
TypeError: Operation 'power' requires the second operand to be an integer array, not <class 'numpy.ndarray over GF(2^9)'>.

# I assume this is what is intended
In [5]: GF(2)**3                                                                                                                 
Out[5]: GF(α^3, order=2^9)

# Which is equivalent to this
In [6]: GF(2) * GF(2) * GF(2)                                                                                                    
Out[6]: GF(α^3, order=2^9)
```

This is even more important for multiplication where there are two types --field multiplication and scalar multiplication -- which are not the same in extension fields!

```python
# Scalar multiplication
In [10]: GF(73)*3                                                                                                                
Out[10]: GF(α^6 + α^3 + 1, order=2^9)

# Which is equivalent to this
In [11]: GF(73) + GF(73) + GF(73)                                                                                                
Out[11]: GF(α^6 + α^3 + 1, order=2^9)

# Field multiplication, which is different
In [12]: GF(73)*GF(3)                                                                                                            
Out[12]: GF(α^7 + α^6 + α^4 + α^3 + α + 1, order=2^9)
```

What are your thoughts on this?

**Comment by iyanmv** [comment]
> This _is_ intentional behavior. I can explain my rationale and you can let me know if it makes sense or could be improved.
> 
> The type checking for arithmetic is _strict_. From your example, what does an integer raised to a finite field element mean? Or, what does a finite field element raised to a finite field element exponent mean?
> 
> I believe the only types that make sense are: integer raised to integer power or finite field element raised to an integer power. This is because the exponent represents an integer number of times to multiply the base.

From a mathematical point of view it doesn't make sense, I agree with you. I also agree with the two types of valid power operations. However, from a practical _pythonic_ coding point of view, I would expect this kind of expressions to do some casting and element wise operations (same as NumPy). Let me show you what I was expecting to happen:

```python
import numpy as np
import galois

GF = galois.GF(2**9)
# 2**GF.Range(0, 10)

GF(2**np.array(GF.Range(0, 10)) % GF.order)
```

In words, first the finite field array gets casted to a regular numpy ndarray with the proper `dtype` (this is done correctly already by the way e.g. `np.array(galois.GF2([0,1]))` gives a `dtype=uint8` array). Then, the power operation is done element wise (for this I believe NumPy internally is transforming 2 to an array of the same size as the exponent array). Then, a modulo operator is done using the order of the original finite field. And finally, the result is put back into a field array. Does this make sense from a mathematical point of view? Hell no! Specially when using other representations instead of the default one. But do you see where I was going?

> Here's an example using `GF(2^9)`. Here `x = GF(3)` isn't the integer 3 -- it's the field element `α + 1` which has the integer representation of 3. So what does `α^(α + 1)` or `2^(α + 1)` really mean? You know? What does a finite field exponent mean in terms of "number of times to multiply the base"?
> 
> ```python
> In [1]: import galois                                                                                                            
> 
> In [2]: GF = galois.GF(2**9, display="poly")                                                                                     
> 
> In [3]: GF(3)                                                                                                                    
> Out[3]: GF(α + 1, order=2^9)
> 
> # What is expected?
> In [4]: GF(2)**GF(3)                                                                                                             
> TypeError: Operation 'power' requires the second operand to be an integer array, not <class 'numpy.ndarray over GF(2^9)'>.
> 
> # I assume this is what is intended
> In [5]: GF(2)**3                                                                                                                 
> Out[5]: GF(α^3, order=2^9)
> 
> # Which is equivalent to this
> In [6]: GF(2) * GF(2) * GF(2)                                                                                                    
> Out[6]: GF(α^3, order=2^9)
> ```
> 
> This is even more important for multiplication where there are two types --field multiplication and scalar multiplication -- which are not the same in extension fields! I feel it's crucial to differentiate these two types of multiplication. And I did so by the argument types.
> 
> ```python
> # Scalar multiplication
> In [10]: GF(73)*3                                                                                                                
> Out[10]: GF(α^6 + α^3 + 1, order=2^9)
> 
> # Which is equivalent to this
> In [11]: GF(73) + GF(73) + GF(73)                                                                                                
> Out[11]: GF(α^6 + α^3 + 1, order=2^9)
> 
> # Field multiplication, which is different
> In [12]: GF(73)*GF(3)                                                                                                            
> Out[12]: GF(α^7 + α^6 + α^4 + α^3 + α + 1, order=2^9)
> ```
> 
> What are your thoughts on this?

Okay, I'm now convinced to keep the strict type checking for arithmetic. But what do you think about allowing some kind of casting? For example, do you see any potential issues in allowing things like these:

```python
import numpy as np
import galois
from galois import GF2

GF = galois.GF(2**9)

a = GF2.Random(10)
b = GF.Random(10)
a + b
# TypeError because orders are different
```

What I would expect (although I admit is a bit arbitrary) is the following:

```python
import numpy as np
import galois
from galois import GF2

GF = galois.GF(2**9)

a = GF2.Random(10)
b = GF.Random(10)
# a + b
GF(a) + b
```

Thanks for the detailed discussion by the way.

**Comment by mhostetter** [comment]
> Does this make sense from a mathematical point of view? Hell no! Specially when using other representations instead of the default one. But do you see where I was going?

I do see where you're going. And it's totally possible to cast arguments to what I think they should be, like in your examples. However, I think the *silent* casting could be misleading, confusing, and create more bugs for users.

Regarding your example, here's an issue I see. I changed the example slightly, but it's the same idea.

```python
In [1]: import galois

In [2]: GF256 = galois.GF(2**8)

In [3]: GF7 = galois.GF(7)

In [4]: a = GF256(100); a
Out[4]: GF(100, order=2^8)

In [5]: b = GF7(5); b
Out[5]: GF(5, order=7)

In [6]: a + b
TypeError: Operation 'add' requires both operands to be GF(2^8) arrays, not [GF(100, order=2^8), GF(5, order=7)].

In [7]: a + b.view(GF256)
Out[7]: GF(97, order=2^8)
```

Trying to add 5 in `GF(7)` to "100" in `GF(2^8)`, with built-in casting we would cast the element in a smaller field to the larger one, presumably. So 5 in `GF(7)` would become "5" in `GF(2^8)`, which is really `α^2 + 1`. They're completely mathematically unrelated. And I doubt a user would want that to happen by default. And if they *really do* want that to happen, it seems safer (and self-documenting) to explicitly cast the element to `GF(2^8)` using `b.view(GF256)` and then add them in the same field.

Thoughts on this?

> Thanks for the detailed discussion by the way.

No problem. Happy to have them to refine my thinking and make the library the best it can be. Thanks for continuing to bring things up.

**Comment by iyanmv** [comment]
Ups, you are right... I always was thinking in prime finite fields only, but the moment you try to do these things with extended fields, things get ugly.

**Comment by iyanmv** [comment]
I think I will close this because I think the only scenario where it would make a bit of sense is with prime finite fields. But then, choosing which field should be use to cast the arrays is completely arbitrary (first, highest order?).
