### ISSUE TITLE
Type hint inconsistency for `shape`

### ISSUE THREAD

**Issue by mhostetter** [mhostetter/galois#234]
![image](https://user-images.githubusercontent.com/12112573/150640746-ad041f7b-99ed-4172-b17c-726cf35fa75a.png)

gave this warning in VS Code

```
Argument of type "tuple[int, int]" cannot be assigned to parameter "shape" of type "int | Tuple[()] | Tuple[int]" in function "Zeros"
  Type "tuple[int, int]" cannot be assigned to type "int | Tuple[()] | Tuple[int]"
    "tuple[int, int]" is incompatible with "int"
    Tuple size mismatch; expected 0 but received 2
    Tuple size mismatch; expected 1 but received 2PylancereportGeneralTypeIssues
```

Need to make `shape` type hint accept a tuple with any number of integer arguments.

**Comment by mhostetter** [comment]
I believe this is the solution: https://stackoverflow.com/a/54747327/11694321.

**Comment by iyanmv** [comment]
I was about to open one issue about this. Good that I checked here first.

By the way, I guess everything will be easier when only `Python >= 3.9` is supported because you will be able to replace `typing` with `collections`, and use `collections.abc.Sequence` for all this.

**Comment by iyanmv** [comment]
Also, I think it's better to use `typing.Sequence` rather than `typing.List` because if you pass a list instead of a tuple, IDE complains.

Look, after changing code to this

```python
def Zeros(
        cls,
        shape: Union[int, Tuple[int, ...], Tuple[int]],
        dtype: Optional[Union[np.dtype, int, object]] = None
    ) -> "FieldArray":
```
I still get the warning
![image](https://user-images.githubusercontent.com/15230534/150857781-e40ef65e-e47f-4ee9-b457-8ead86efd5ce.png)

With this code seems to work

```python
def Zeros(
        cls,
        shape: Union[int, Sequence[int, ...], Tuple[int]],
        dtype: Optional[Union[np.dtype, int, object]] = None
    ) -> "FieldArray":
```

**Comment by mhostetter** [comment]
I heard of `Sequence`, but I was under the wrong impression of how it worked. I believe `Sequence[int, ...]` is not a valid type hint syntax for `Sequence`, but I think `Sequence[int]` does what we want.

This code gives me no warnings.

```python
    @classmethod
    def Zeros(
        cls,
        shape: Union[int, Sequence[int]],
        dtype: Optional[Union[np.dtype, int, object]] = None
    ) -> "FieldArray":
```

![image](https://user-images.githubusercontent.com/12112573/150860322-d3e5ccdf-0f44-474f-ba05-42e163cee973.png)

**Comment by iyanmv** [comment]
It's a bit tricky for the moment I think. I get different results with different versions of python. I think let's just keep using `Union[List, Tuple]` instead of `Sequence`.

What do you think of using this?

```
shape: Union[int, Tuple[int, ...], List[int, ...]]
```
I don't get any warnings trying from Python 3.7 to 3.10.

**Comment by iyanmv** [comment]
Never mind... I think PyCharm needed some extra time when changing from one interpreter to another. `Sequence[int]` works for me as well.

**Comment by mhostetter** [comment]
@iyanmv please keep opening issues or commenting when you find weird/strange type hint warnings/errors. That's really helpful for me! 👍
