### ISSUE TITLE
`FieldArray(..., copy=False)` does not work as intended

### ISSUE THREAD

**Issue by mhostetter** [mhostetter/galois#275]
Below, `c` is expected to act the same as `a`.

```python
In [1]: import numpy as np

In [2]: import galois

In [3]: x = np.array([1, 2, 3]); x
Out[3]: array([1, 2, 3])

In [4]: GF = galois.GF(7)

In [5]: a = x.view(GF); a
Out[5]: GF([1, 2, 3], order=7)

In [6]: b = GF(x, copy=True); b
Out[6]: GF([1, 2, 3], order=7)

In [7]: c = GF(x, copy=False); c
Out[7]: GF([1, 2, 3], order=7)

In [8]: x[0] = 0

In [9]: a, b, c
Out[9]: (GF([0, 2, 3], order=7), GF([1, 2, 3], order=7), GF([1, 2, 3], order=7))
```

**Comment by iyanmv** [comment]
From [`numpy.array`](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy-array) docs:

> If true (default), then the object is copied. Otherwise, a copy will only be made if `__array__` returns a copy, if obj is a nested sequence, or if a copy is needed to satisfy any of the other requirements ([dtype](https://numpy.org/doc/stable/reference/generated/numpy.dtype.html#numpy.dtype), order, etc.).

In this case, `copy=False` is ignored because a copy needs to be done to cast from `np.int64` to `np.uint8`.

If you define `x = np.array([1, 2, 3], dtype=np.uint8)`, then `copy=False` is respected.

I don't think this is a bug. Would you like to handle this by printing some warning?

**Comment by mhostetter** [comment]
Ah! Thanks for pointing this out @iyanmv. I didn't realize the change in dtype was causing the copy, although it makes perfect sense.

I was able to also get `copy=False` to work when matching the `dtype` kwarg.

```python
In [1]: import numpy as np

In [2]: import galois

In [3]: x = np.array([1, 2, 3]); x
Out[3]: array([1, 2, 3])

In [4]: GF = galois.GF(7)

In [5]: a = x.view(GF); a, a.dtype
Out[5]: (GF([1, 2, 3], order=7), dtype('int64'))

In [6]: b = GF(x); b, b.dtype
Out[6]: (GF([1, 2, 3], order=7), dtype('uint8'))

In [7]: c = GF(x, copy=False); c, c.dtype
Out[7]: (GF([1, 2, 3], order=7), dtype('uint8'))

In [8]: d = GF(x, copy=False, dtype=np.int64); d, d.dtype
Out[8]: (GF([1, 2, 3], order=7), dtype('int64'))

In [9]: x[0] = 0

In [10]: a, b, c, d
Out[10]: 
(GF([0, 2, 3], order=7),
 GF([1, 2, 3], order=7),
 GF([1, 2, 3], order=7),
 GF([0, 2, 3], order=7))
```

Perhaps a sentence in the `copy` parameter mentioning a copy may be performed for other reasons may be helpful. But, I agree, I don't think this is a bug.
