### ISSUE TITLE
PyInstaller sqlite3 conway database error

### ISSUE THREAD

**Issue by red-opal** [mhostetter/galois#330]
When trying to run the following code that I built with PyInstaller, I get the error below thrown.

```
import galois

GF8 = galois.GF(2**8, 'x^8+x^4+x^3+x+1')
GF1 = galois.GF(2)
GF32 = galois.GF(2**32)
```
(This runs fine if executed as a python script.)
```
Traceback (most recent call last):
  File "galois-pyinst-test.py", line 5, in <module>
  File "galois\_fields\_factory.py", line 224, in GF
  File "galois\_fields\_factory.py", line 332, in GF_extension
  File "galois\_fields\_factory.py", line 970, in conway_poly
  File "galois\_databases\_conway.py", line 20, in __init__
sqlite3.OperationalError: unable to open database file
[1984] Failed to execute script 'galois-pyinst-test' due to unhandled exception!
```
Is this an error with galois? I've gone through the basic PyInstaller debug checklist, none seem to apply here.
Otherwise I can ask for help from PyInstaller.

**Comment by mhostetter** [comment]
Hey. I'm unfamiliar with PyInstaller, but just did a quick google search. So are you using PyInstaller to bundle `galois` into a broader application?

The issue arises from the default irreducible polynomial in `galois.GF()` invoking `galois.conway_poly()` which opens the Conway polynomial database `galois/_databases/conway_polys.db`, which doesn't seem to be present in your case. My hunch is that the PyInstaller packager isn't including the package data from `galois`.

When building this package, I had to indicate to include package data (non `.py` files) and where to find those files. Specifically here, `galois/_databases/*.db`. There might be a similar setting in PyInstaller.

https://github.com/mhostetter/galois/blob/53c622e88a4e3e65758098a28744b1fb0428b457/setup.cfg#L45-L58

**Comment by mhostetter** [comment]
Perhaps this would work: https://pyinstaller.readthedocs.io/en/stable/spec-files.html#using-data-files-from-a-module

Although you'd need to manually indicate which data files to include. At present, the only non-Python file is `conway_polys.db`.

Perhaps try this?

```python
a = Analysis(...
     datas= [ ('galois/_databases/conway_polys.db', 'galois' ) ],
     ...
     )
```

**Comment by mhostetter** [comment]
@red-opal did this work for you?

**Comment by red-opal** [comment]
Somehow I broke my PyInstaller installation, so unfortunately I have no idea.
It keeps throwing [Errno 13], both with and without your fix. Not the most forgiving of programs.
I'll try and get PyInstaller sorted out first.

**Comment by red-opal** [comment]
Finally got back around to this, turns out updating pyinstaller from 4.9 to 5.0 fixed Errno 13.
Your fix didn't work unfortunately, however I managed to solve it myself by setting the polynomial manually in my source code. Of course it's more of a hack than a fix, but it's good enough.

```
C:\Users\******>pyinstaller ***.spec
94 INFO: PyInstaller: 5.0
94 INFO: Python: 3.10.4
106 INFO: Platform: Windows-10-10.0.19043-SP0
110 INFO: UPX is not available.
111 INFO: Extending PYTHONPATH with paths
['C:\\Users\\******']
394 INFO: checking Analysis
517 INFO: Appending 'datas' from .spec
Unable to find "galois\_databases\conway_polys.db" when adding binary and data files.
```

Honestly .spec files (and pyinstaller in general) are pretty overwhelming. If I can even get the .spec file to work by sacrificing half the stuff I wanted it to do, other things break immediately. ¯\\\_(ツ)\_/¯

**Comment by mhostetter** [comment]
Can you share your `.spec` file? Perhaps I might notice something.

It says `Unable to find "galois\_databases\conway_polys.db" when adding binary and data files.` Did you clone galois manually or install from pip? Is there a `galois/` folder in the current folder?

Otherwise, I would open an issue with PyInstaller. The issue definitely arises from not including package data correctly.

**Comment by mhostetter** [comment]
I think this issue is related to `PyInstaller`, not `galois`. Feel free to re-open if you need more assistance from me.

**Comment by Map1e0823** [comment]
a = Analysis(...
     datas= [ ('venv/Lib/site-packages/galois/_databases/conway_polys.db', 'galois/_databases' ) ],
     ...
     )
Maybe this could help. 
I use pycharm for the project btw. venv is the folder where the virtual environment of the project is located
In fact, you can create a folder "galois/_databases" in the "_internal" folder and put the required db files in it.
