### ISSUE TITLE
Bump numpy version?

### ISSUE THREAD

**Issue by iyanmv** [mhostetter/galois#365]
Hi,

[`numba 0.55.2`](https://github.com/numba/numba/releases/tag/0.55.2) now supports `numpy 1.22.x`. This is great news because now it is possible to use `galois` with numpy versions not affected by known security issues (see, for example, [this](https://github.com/numba/numba/issues/8025)), i.e. `numpy >= 1.22.2`

Is it okay to bump the numpy version in setup.cfg? i think only one line needs to be changed. I have just run all the tests without issues.

I will create a pull request and we can discuss there if you think I'm missing something.

**Comment by mhostetter** [comment]
Thanks again for this PR!

**Comment by iyanmv** [comment]
This PR was zero effort :see_no_evil: Thank you for keep working on this package!
