### ISSUE TITLE
Extremly Huge Power Finite Fields

### ISSUE THREAD

**Issue by Rz1010** [mhostetter/galois#445]
When I try to define GF = galois.GF(2**571) it is taking so much time. 

(Now Matt updated the functionality to be able to separate characteristics and degree GF = galois.GF(2,571)

**Comment by Rz1010** [comment]
Matt recommended using:

GF = galois._fields._factory._GF_extension(2,571,irreducible_poly_ = "x^571 + x^10 + x^5 + x^2 + 1" ,alpha=2, verify=False)

As a quick fix, which executes instantaneously

**Comment by Rz1010** [comment]
verify=False is used to skip verifying the irreducible polynomial is irreducible and that the provided primitive element is a multiplicative generator. This requires factoring p^m - 1, which is slow...

**Comment by mhostetter** [comment]
Yes. I added an extra call signature to [`galois.GF()`](https://mhostetter.github.io/galois/latest/api/galois.GF/). Also, I added [a note](https://mhostetter.github.io/galois/latest/basic-usage/array-classes/#fieldarray-subclasses) in the documentation about speeding up creation of large finite fields.

Using the private function `galois._fields._factory.GF_extension()` was a stopgap and is no longer necessary after v0.3.0.

**Comment by mhostetter** [comment]
With v0.3.2 (to be released today), the above example now runs much faster, even with factoring `p**m` and verification.

```python
In [1]: import galois

# In v0.3.2
In [2]: %time GF = galois.GF(2**571, irreducible_poly="x^571 + x^10 + x^5 + x^2 + 1", primitive_element="x")
CPU times: user 1.7 s, sys: 0 ns, total: 1.7 s
Wall time: 1.56 s

In [3]: print(GF.properties)
Galois Field:
  name: GF(2^571)
  characteristic: 2
  degree: 571
  order: 7729075046034516689390703781863974688597854659412869997314470502903038284579120849072387533163845155924927232063004354354730157322085975311485817346934161497393961629646848      
  irreducible_poly: x^571 + x^10 + x^5 + x^2 + 1
  is_primitive_poly: True
  primitive_element: x
```
