### ISSUE TITLE
expressions that should evaluate to zero return a gibberish number

### ISSUE THREAD

**Issue by aleksmark98** [mhostetter/galois#478]
This happens only in non-prime fields, ie 11^2, 3^3.

```python
>>> import galois
>>> GF = galois.GF(121)
>>> p = 11
>>> p*p % 121
0
>>> p = GF(p)
>>> p*p # should be 0
GF(53, order=11^2)
```

**Comment by mhostetter** [comment]
In extension fields `GF(p^m)`, `p*p % p^m` does not equal zero. That is only true in prime fields where `m = 1`. In extension fields, the element "`p`" represents the polynomial `x` in `GF(p)[x]` and `p*p` represents `x^2`. However, elements in `GF(11^2)` can have degree at most 1, so `x^2` must be reduced modulo the irreducible polynomial of the field, which is `x^2 + 7x + 2`. `x^2 % x^2 + 7x + 2 = 4x + 9` and `4x + 9` is represented in decimal as `4*11 + 9 = 53`.

```python
In [1]: import galois

In [2]: GF = galois.GF(11**2, repr="poly")

In [3]: print(GF.properties)
Galois Field:
  name: GF(11^2)
  characteristic: 11
  degree: 2
  order: 121
  irreducible_poly: x^2 + 7x + 2
  is_primitive_poly: True
  primitive_element: x

In [4]: a = GF(11); a
Out[4]: GF(α, order=11^2)

In [5]: a * a
Out[5]: GF(4α + 9, order=11^2)
```

**Comment by aleksmark98** [comment]
You've made it clear that I have some reading to do. Thank you for the clarification and I apologize for reporting this as an issue.
