### ISSUE TITLE
Support for numpy v1.25

### ISSUE THREAD

**Issue by iyanmv** [mhostetter/galois#491]
All tests pass on numpy 1.25 with numba 0.57.1 compiled with [this patch](https://github.com/numba/numba/issues/8698), which should be included in numba 0.58. Tested both with the latest release and master branch.

But there are some deprecation warnings because of [this change](https://github.com/numpy/numpy/pull/10615) in numpy.

> DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)

Easy to fix, I will open a PR later today 😉

**Comment by mhostetter** [comment]
Support for NumPy 1.25 added in v0.3.6.
