### ISSUE TITLE
print(GF9.repr_table()) misses out last element

### ISSUE THREAD

**Issue by m3guitar** [mhostetter/galois#503]
Also happens with print(GF16.repr_table()). Spotted on this page, https://galois.readthedocs.io/en/v0.0.21/tutorials/intro-to-extension-fields.html. 

My apologies if I have overlooked something obvious.

ole

**Comment by dimbleby** [comment]
you've counted wrong - there are nine (and sixteen) entries in those tables, as expected

(also you're looking at an old version of the docs)

**Comment by mhostetter** [comment]
Sorry the delayed response. I agree with what David said.

If you were wondering where `x^8` is in the table, `x^8 == x^0 == 1`.

![image](https://github.com/mhostetter/galois/assets/12112573/c14c0403-e970-4454-86b6-721eb36dbe46)
