### ISSUE TITLE
[bug] Prime factorization in the error message

### ISSUE THREAD

**Issue by MrVeka** [mhostetter/galois#556]
Hi, when trying to create a Galois field of 50 we get this error message : 
`Argument 'order' must be a prime power, not 50 = 2**1 + 5**2.`

I think it should have been `2**1 * 5**2` or  `2^1 * 5^2`, I'ill try to implement the latter if it's ok.

**Comment by mhostetter** [comment]
Thanks for the report and PR!

**Comment by mhostetter** [comment]
Released in v0.4.1.
