### ISSUE TITLE
Problems using exponentiation arithmetic in galois field

### ISSUE THREAD

**Issue by janicebeinrot** [mhostetter/galois#584]
I've got the following bit of code where I'm trying to verify that the Galois library's result for (a^b)^c is equal to a^(b * c)

```
import galois

GF = galois.GF(2**8)
print(GF.properties)

a = GF('2')
b = GF('3')
c = GF('4')

r1 = a ^ (b * c)       # Gives incorrect/inconsisten results
r2 = (a ^ b) ^ c       # Gives incorrect/inconsisten results

# r1 = a ** (b * c)    # Gives Python Errors
# r2 = (a ** b) ** c   # Gives Python Errors

print(r1)
print(r2)
```

Was wondering if you could direct me to the documentation page that discusses power/exponentiation functionality of the Galois lib.

----------

As a side question, if a,b and c are polynomials would the original equality still hold true?

**Comment by mhostetter** [comment]
There are two errors here:

1. `^` in Python is bitwise XOR. `**` in Python is exponentiation. So, `r1 = a ** (b * c)` is implementing what you want to test.
2. In exponentiation, the exponent must be an integer, not a finite field element.

Here is the correct example.

```python
import galois

GF = galois.GF(2**8)

a = GF(111)
b = 3
c = 4

r1 = a ** (b * c)
r2 = (a ** b) ** c

print(r1)
print(r2)
```

```
138
138
```

The documentation is located here https://mhostetter.github.io/galois/latest/basic-usage/array-arithmetic/#standard-arithmetic.

**Comment by janicebeinrot** [comment]
@mhostetter  thank-you for the quick reply. 

So to confirm, only positive integer values can be used for the power and not a field element, as exponentiation in FF math is only defined for integer powers, is that correct?

**Comment by mhostetter** [comment]
The exponent can be any integer. This is from the definition of exponentiation.

```python
assert a ** 2 == a * a
assert a ** 1 == a
assert a ** 0 == GF(1)
assert a ** -1 == GF(1) / a
assert a ** -2 == GF(1) / (a * a)
```

What would it mean for the exponent to be a finite field element?

**Comment by janicebeinrot** [comment]
thanks that make sense.
