### ISSUE TITLE
Missing database

### ISSUE THREAD

**Issue by sleveque** [mhostetter/galois#65]
Something is wrong with the pip package.

```
$ sudo python3 -m pip install galois
Collecting galois
  Using cached galois-0.0.11-py3-none-any.whl (56 kB)
Requirement already satisfied: numpy>=1.17.3 in /usr/lib/python3/dist-packages (from galois) (1.19.5)
Requirement already satisfied: numba>=0.49 in /usr/local/lib/python3.9/dist-packages (from galois) (0.51.2)
Requirement already satisfied: llvmlite<0.35,>=0.34.0.dev0 in /usr/local/lib/python3.9/dist-packages (from numba>=0.49->galois) (0.34.0)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from numba>=0.49->galois) (52.0.0)
Installing collected packages: galois
Successfully installed galois-0.0.11
$ cat mwe.py 
import galois

gf = galois.GF2
$ python3 mwe.py 
Traceback (most recent call last):
  File "mwe.py", line 1, in <module>
    import galois
  File "/usr/local/lib/python3.9/dist-packages/galois/__init__.py", line 259, in <module>
    GF2.prim_poly = conway_poly(2, 1)
  File "/usr/local/lib/python3.9/dist-packages/galois/__init__.py", line 240, in conway_poly
    db = ConwayDatabase()
  File "/usr/local/lib/python3.9/dist-packages/galois/conway.py", line 20, in __init__
    self.conn = sqlite3.connect(DATABASE_FILE)
sqlite3.OperationalError: unable to open database file

$ sudo updatedb
$ locate conway_polys.db
$
```

Am I expected to run anything after installation to generate the database? I didn't see anything about it in the documentation.

**Comment by sleveque** [comment]
My workaround is quite ugly:
- collect and run the [create_conway_polys_database.py script](https://github.com/mhostetter/galois/blob/master/scripts/create_conway_polys_database.py)
- move the generated database to the pip `galois` installation tree 
- patch the `DATABASE_FILE` in `galois/conway.py`

**Comment by mhostetter** [comment]
Thanks for the report! The database should be "shipped" with the package. I placed it in the package manifest. Something must've been lost in translation. I'll get to the bottom of this.

**Comment by mhostetter** [comment]
Oops -- didn't mean to auto-close the issue. I fixed the packaging issue in #66. You should be able to `python3 -m pip install -U galois` to install `0.0.12`.. It might actually be safer for you to uninstall first and then reinstall given you made manual tweaks. Please report back if you have success/failure. Thanks.

**Comment by sleveque** [comment]
It works fine, now. Thank you

**Comment by mhostetter** [comment]
@sleveque No problem. This package is under active development. So any thoughts, comments, feature requests, etc would be appreciated.
