### ISSUE TITLE
(blanket issue) add features found in libgf2

### ISSUE THREAD

**Issue by jason-s** [mhostetter/galois#77]
Hey, it looks like you've done a really thorough job here, at least at first glance.

I have a library, [libgf2](https://foss.heptapod.net/math/libgf2), which no one else actually uses, that has a couple of features that might be missing from the `galois` library, including:

- LFSR support including Berlekamp-Massey for finding the characteristic polynomial of an LFSR sequence
- quotient rings using specified polynomials
- discrete logarithm (in the easier cases)

Give it a look-see... I have zero time right now to help but maybe in a year or so my schedule will ease up and I can help contribute here.

**Comment by mhostetter** [comment]
Hey, thanks for reaching out! I will definitely check out your library. Let's use this issue to track the addition of the extra functionality you mentioned. I may have some free time before you, but we'll track it here. LFSRs and BMA are definitely on my radar. I have a previous implementation of them from a different project. Quotient rings would be nice. And `galois` needs improvement on computing discrete logarithms. I only have the naive algorithm implemented currently.

How would you like to proceed? If I have free time and find inspiration from your code, can I add something similar to `galois`. And if so, how would you like me to credit you?

**Comment by jason-s** [comment]
Permission granted on copying anything from libgf2 as long as you give credit + a reference to it. (+ to [Part 1](https://www.embeddedrelated.com/showarticle/1065.php) of my articles on LFSRs if you don't mind) My name is Jason Sachs. I picked the Apache license for libgf2 but I'm open to granting permission for any permissive license; MIT is fine.

I'm curious how performance compares; I was able to get reasonable performance from Python via Cython for multiplication + modulo, but didn't go any further. I'm very familiar with numba, haven't tried to use it for this stuff yet so it's exciting to see this.

There's also a Java library [jlibgf2](https://foss.heptapod.net/math/jlibgf2) which isn't as mature, but it does have a number of primitive polynomial generation methods implemented whereas libgf2 does not. (See [Part XVIII](https://www.embeddedrelated.com/showarticle/1193.php))

**Comment by mhostetter** [comment]
Sounds good. I'll track any progress I make here, for your awareness.

Please let me know your thoughts on performance. In particular, any areas that appear to be slow. A big goal of this project is speed and performance. So, bad news is good news in that I'll know where to target for improvement. (I'm currently working on a PR to eek out some performance improvements). So if/when you run it, please let me know what version you were using. (What might be relevant to you... I found a dumb implementation detail that cause slow generation of `GF(2^m)` lookup tables. That's much much faster now. See https://github.com/mhostetter/galois/pull/74#issuecomment-825989166)

I'm interested to view your primitive polynomial routines. Currently, the only primitive polynomial generation available is a Conway polynomial from [Frank Luebeck's database](http://www.math.rwth-aachen.de/~Frank.Luebeck/data/ConwayPol/index.html).

**Comment by mhostetter** [comment]
By the way, I just started looking through your LFSR articles on EmbeddedRelated. They're really impressive and thorough. I plan to go through each of them, actually. I'm sure I'll pick up some handy things. I'll make sure to add a reference. Kudos, though. Very impressive!

**Comment by jason-s** [comment]
hey, thanks!

I should note that libgf2 is written for Python 2.7. I am now current with Python 3.x for my day-to-day work, but haven't had time to go back and update the earlier stuff. Usually the only differences are just `print` statements and use of `xrange`.

**Comment by jason-s** [comment]
>Hey, thanks for reaching out!

Well, I should thank you for [your answer on StackOverflow to my question from 2013](
https://stackoverflow.com/questions/19350395/python-jit-for-known-bottlenecks/67235318#67235318), otherwise I wouldn't have found out about this project.

**Comment by mhostetter** [comment]
Hey @jason-s! Just thought I would re-ping this thread. A lot has happened in 11 months. I added Fibonacci and Galois LFSRs and the Berlekamp-Massey algorithm, as previously mentioned, along with lots more.

Just wanted to touch base and see if you thought there were other things this library could benefit from or any places where collaboration could happen. No worries if not!

**Comment by mhostetter** [comment]
I'm going to close this issue due to inactivity. Jason, feel free to reach out and/or open future issues if you find bugs or would like to collaborate in some way.
